### ISSUE TITLE
Show Humidity Card

### ISSUE THREAD

**Issue by LBeghini** [gardim/gardim-mvp-deprecated#7]
Create a Card component to show the humidity values of the plant.

The Card should receive:
- Title
- Percentage
- Status

Assertions:
- [x] Given the values ESP returns, convert them to percentage
- [x] From the percentage, generate a status for the plant, that can vary from:
    -  🔴  `Alert`:  percentage is less than minimum, or above the maximum
    - 🟡  `Caution`:  percentage is only 5 above the minimum, or only 5 below the maximum
    - 🟢  `Good`: between the minimum and maximum range

**Comment by LBeghini** [comment]
@BrendowAlisson preciso de variáveis de teste para poder validar o app.
Dado a planta Samambaia como exemplo:
```js
  {
    name: 'Samambaia',
    type: 'samambaia',
    humidity: {
      min: 40,
      max: 80,
    },
  },
```
Preciso preencher a seguinte tabela de valores limite para testar na aplicação:

| Status  | Limite | Porcentagem  | Valor ESP |
|---------|--------|--------------|-----------|
| 🔴  Alert   | 🔽 Minimo | 39 %          |           |
| 🔴 Alert   | 🔼 Maximo | 81 %          |           |
| 🟡 Caution | 🔽Minimo | 44 %          |           |
| 🟡 Caution | 🔼Maximo | 76 %          |           |
| 🟢 Good    | 🔽Minimo | 45 %          |           |
| 🟢 Good    | 🔼Maximo | 75 %          |           |

A função que me passou não está retornando os valores esperados, dando porcentagens acima de 100%. Dado:
```js
const percentage = 100 * ((4095 - value) / 1795);
```
Passando o valor `2300`, esta retorna `100`,
Porém, para `1500`, esta retorna `144.56824512534817`

Poderia preencher a tabela por favor, e revisar/explicar o retorno da função?

**Comment by BrendowAlisson** [comment]
@LBeghini Isso já era esperado de acontecer na equação. 
Entretanto pelos testes feitos com o sensor, até o momento, mostrou que quando o mesmo está imerso em água, possui uma leitura que não passa dos 2300 (chegou próximo). 
Como o estado de água pura é o máximo de umidade, optou-se pelos 2300 como limite.
Deste modo, não é possível em uma leitura real ter resultados maiores que 100%, já que não irá passar dos 2300.
Sabendo-se disso, o resultado de 1500 que você utilizou **não será um parâmetro obtido em testes reais**.

A função para encontrar os valores da ESP pela porcentagem será:

```
value = (-17.95 * percentage) + 4095
````
Então os valores de leitura serão:

| Status  | Limite | Porcentagem  | Valor ESP |
|---------|--------|--------------|-----------|
| 🔴  Alert   | 🔽 Minimo | 39 %          |     3394,9     |
| 🔴 Alert   | 🔼 Maximo | 81 %          |     2641,05      |
| 🟡 Caution | 🔽Minimo | 44 %          |     3305,2      |
| 🟡 Caution | 🔼Maximo | 76 %          |       2730,8    |
| 🟢 Good    | 🔽Minimo | 45 %          |   3287,3        |
| 🟢 Good    | 🔼Maximo | 75 %          | 2748,8          |

Quaisquer dúvidas, estou a disposição.

**Comment by LBeghini** [comment]
Fazendo alguns testes, adaptei um pouco esses valores para fazer testes mais precisos. 

A função `Math.round()` do Javascript é muito imprecisa, e para um mesmo valor, varia o resultado. Também deixei os valores da ESP como inteiros, para simular com precisão o que seria recebido no aplicativo.

| Status  | Limite | Porcentagem  | Valor ESP |
|---------|--------|--------------|-----------|
| 🔴  Alert   | 🔽 Minimo | 39 %          |     3400     |
| 🔴 Alert   | 🔼 Maximo | 81 %          |     2640      |
| 🟡 Caution | 🔽Minimo | 44 %          |     3380      |
| 🟡 Caution | 🔼Maximo | 76 %          |       2730    |
| 🟢 Good    | 🔽Minimo | 45 %          |   3290        |
| 🟢 Good    | 🔼Maximo | 75 %          | 2750          |
