### ISSUE TITLE
Humidity Sensor

### ISSUE THREAD

**Issue by BrendowAlisson** [gardim/gardim-mvp-deprecated#8]
The humidity sensor used in this application doesn't support precisive data to say the percentage of humidity in dirt. So, to pass this problem, we add some intervals with the respective states of dirt:
- dry
- little damp
- damp
- very damp
- soggy

The states and results in analog port of microcontroller is shown below:
 
|    Status | Analog Port Result |
|:-----------:|:------------------:|
|     Dry     |     4095 - 3500    |
| Little Damp |     3500 - 3000    |
|     Damp    |     3000 - 2000    |
|  Very Damp  |     2000 - 1600    |
|    Soggy    |      1600 - 0      |

Those changes need to be added on the app.

**Comment by LBeghini** [comment]
Como as mudanças não foram implementadas no aplicativo, estou reabrindo a issue. Esta só se conclui se não tiver mais problemas tanto da parte do hardware, quanto da parte do software.

**Comment by LBeghini** [comment]
Eu utilizei a seguinte referência para determinar os níveis de alerta das plantas:
```js
import { DRY, LITTLE_DAMP, SOGGY, VERY_DAMP } from './Status';

var INFO = [
  {
    name: 'Samambaia',
    type: 'samambaia',
    humidity: {
      min: LITTLE_DAMP,
      max: VERY_DAMP,
    },
  },
  {
    name: 'Cróton',
    type: 'croton',
    humidity: {
      min: LITTLE_DAMP,
      max: VERY_DAMP,
    },
  },
  {
    name: 'Orquídea',
    type: 'orquidea',
    humidity: {
      min: LITTLE_DAMP,
      max: LITTLE_DAMP,
    },
  },
  {
    name: 'Espada de São Jorge',
    type: 'espada',
    humidity: {
      min: LITTLE_DAMP,
      max: LITTLE_DAMP,
    },
  },
  {
    name: 'Bromélia',
    type: 'bromelia',
    humidity: {
      min: VERY_DAMP,
      max: SOGGY,
    },
  },
  {
    name: 'Suculenta',
    type: 'suculenta',
    humidity: {
      min: DRY,
      max: LITTLE_DAMP,
    },
  },
  {
    name: 'Cacto',
    type: 'cacto',
    humidity: {
      min: DRY,
      max: LITTLE_DAMP,
    },
  },
];

export default INFO;

```

Dessa forma, as atualização de status são:
    - 🔴  `Alert`:  se a planta não estiver dentro do intervalo
    - 🟡  `Caution`:  se a planta estiver próxima de sair de seu intervalo, utilizando 100 como limite
    - 🟢  `Good`: se estiver dentro do seu limite
